
[[test]]
stdin = "5\n5\n"
output = "10\n"

[[test]]
stdin = "11\n5\n"
output = "16\n"






[[test]]
function = "add"
args = [1,3]
return = 4


[[test]]
function = "add"
args = [3,3]
return = 6






[[test]]
description = "Add 1 + 3"
function = "add"
args = [1, 3]
returns = 4

[[test]]
description = "Add 3 + 3"
function = "add"
args = [3, 3]
returns = 6